stand_open: true
categories:
  - name: CrÃªpes
    id: crepes
    emote: ğŸ¥
    toppings:
      options:
        - name: Nutella
          price: 1.25
        - name: Sucre
          price: 0.5
        - name: Citron
          price: 0.5
      recommandations:
        - name: Sucre + Citron
          price: 1.25

  - name: Barbe Ã  papa
    id: barbe-a-papa
    emote: ğŸ­
    price: 1.5

